INSERT INTO MEMBER (ID, USERNAME, PASSWORD, EMAIL, CREATED_DATE, UPDATED_DATE)
VALUES (1, 'user1', '$2a$10$RipmJ2.1x5wRiO5Dx4a2SeAZRfWDiKCQEezI9TzAiP5yAfiH5jIhK', 'nana@naver.com', NOW(), NOW());
INSERT INTO MEMBER (ID, USERNAME, PASSWORD, EMAIL, CREATED_DATE, UPDATED_DATE)
VALUES (2, 'user2', '$2a$10$9bixt37laSFs1yvC6F/b9u4WUNqaJVRcxLPdjJU2vAZBDnxgmzmxq', 'nana2@naver.com', NOW(), NOW());

INSERT INTO MEMBER_ROLE_SET (MEMBER_ID, ROLE_SET) VALUES (1, 'ROLE_USER');
INSERT INTO MEMBER_ROLE_SET (MEMBER_ID, ROLE_SET) VALUES (2, 'ROLE_USER');