DROP TABLE IF EXISTS member_role_set;
DROP TABLE IF EXISTS member;

CREATE TABLE member
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY,
    created_date TIMESTAMP(6),
    updated_date TIMESTAMP(6),
    email        VARCHAR(255),
    password     VARCHAR(255),
    username     VARCHAR(255),
    PRIMARY KEY (id)
);

CREATE TABLE member_role_set
(
    member_id BIGINT NOT NULL,
    role_set  VARCHAR(255) CHECK (role_set IN ('ROLE_USER', 'ROLE_ADMIN'))
);

ALTER TABLE IF EXISTS member_role_set
    ADD FOREIGN KEY (member_id)
    REFERENCES member;